version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
